"""SLURM substrate for the cluster abstraction.

Owns everything SLURM-specific: sbatch rendering, ``sbatch``/``squeue``/
``scancel`` lifecycle, QoS preflight against the cluster cache, and
``uv`` worker-env bootstrap.  Public entrypoints take a name + config and
return the same :class:`ClusterInfo` shape every other substrate would.

Future ``_k8s.py`` mirrors this surface.
"""
from __future__ import annotations

import logging
import os
import signal
import socket
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml
from astra.helpers import load_yaml

from lightcone.engine.clusters._common import (
    ClusterInfo,
    ClusterRecord,
    ClusterSpec,
    WorkerPool,
    env_path_for_site,
    expand_path,
    get_cache_dir,
    load_cluster_config,
    parse_walltime_seconds,
    read_record,
    read_scheduler_address,
    spec_from_config,
    state_path,
    walltime_to_slurm,
    write_record,
)
from lightcone.engine.site_registry import SITE_DEFAULTS, detect_site

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Site-keyed SLURM cluster discovery cache (sacctmgr / scontrol output)
# ---------------------------------------------------------------------------


def _cache_path(site: str) -> Path:
    return get_cache_dir() / f"{site}.slurm.yaml"


def load_slurm_cache(site: str) -> Any:
    """Load cached SLURM cluster info (sacctmgr/scontrol) for *site* or ``None``."""
    from lightcone.engine.clusters._slurm_info import cluster_info_from_dict

    try:
        data = load_yaml(_cache_path(site))
    except FileNotFoundError:
        return None
    return cluster_info_from_dict(data) if data else None


def save_slurm_cache(site: str, info: Any) -> Path:
    from lightcone.engine.clusters._slurm_info import cluster_info_to_dict

    # Keep raw yaml.dump here — we want the autogenerated header comment.
    path = _cache_path(site)
    with open(path, "w") as f:
        f.write("# AUTO-GENERATED by `lc cluster refresh-cache`. Do not edit.\n")
        yaml.dump(cluster_info_to_dict(info), f, default_flow_style=False, sort_keys=False)
    return path


def is_cache_stale(site: str, max_age_days: int = 30) -> bool:
    try:
        data = load_yaml(_cache_path(site))
    except FileNotFoundError:
        return True
    if not data or not data.get("timestamp"):
        return True
    try:
        ts = datetime.fromisoformat(data["timestamp"])
        return (datetime.now(UTC) - ts).days > max_age_days
    except (ValueError, TypeError):
        return True


def refresh_slurm_cache(site: str) -> Any:
    """Re-query SLURM (sacctmgr/scontrol) and rewrite the cache for *site*."""
    from lightcone.engine.clusters._slurm_info import discover_cluster

    info = discover_cluster()
    save_slurm_cache(site, info)
    return info


# ---------------------------------------------------------------------------
# Sbatch rendering
# ---------------------------------------------------------------------------


def _resolve_worker_init(spec: ClusterSpec) -> str:
    """Return the bash snippet that activates the worker env on compute nodes."""
    if spec.worker_init:
        return spec.worker_init.rstrip() + "\n"
    site_defaults = SITE_DEFAULTS.get(spec.site, {})
    template = (site_defaults.get("slurm") or {}).get("worker_init_template")
    if template:
        return template.rstrip() + "\n"
    return f"source $HOME/.lightcone/envs/{spec.site}/bin/activate\n"


def _resources_to_dask_arg(resources: dict[str, int]) -> str:
    """Translate ``{"GPU": 4}`` → ``"GPU=4"`` for ``dask worker --resources``."""
    return ",".join(f"{k}={v}" for k, v in sorted(resources.items()))


def _total_nodes(spec: ClusterSpec) -> int:
    return sum(w.nodes for w in spec.workers)


def _argv_to_sbatch_line(argv: list[str]) -> str:
    """Format ``_worker_srun_argv`` output as a shell line for the sbatch script.

    Groups ``--flag value`` pairs onto one token, double-quotes values that
    need shell expansion or contain spaces/equals, and joins with backslash
    continuations matching the existing sbatch script style.
    """
    parts: list[str] = []
    i = 0
    while i < len(argv):
        tok = argv[i]
        if tok == "dask" and i + 1 < len(argv) and argv[i + 1] == "worker":
            parts.append("dask worker")
            i += 2
            continue
        if tok.startswith("--") and "=" not in tok and i + 1 < len(argv):
            value = argv[i + 1]
            if value.isdigit():
                parts.append(f"{tok} {value}")
            else:
                parts.append(f'{tok} "{value}"')
            i += 2
            continue
        parts.append(tok)
        i += 1
    return " \\\n     ".join(parts)


def _worker_srun_argv(
    pool: WorkerPool,
    sched_file: str,
    local_dir: str,
    *,
    per_pool_constraint: bool = False,
) -> list[str]:
    """Build raw argv for one ``srun … dask worker …`` invocation.

    Used directly by :func:`attach_to_allocation` (subprocess.Popen) and
    by :func:`render_sbatch` (which shell-quotes selected tokens for the
    sbatch script).  ``sched_file`` and ``local_dir`` may be either literal
    paths (for Popen) or shell-variable references (for sbatch).
    """
    args = [
        "srun",
        f"--nodes={pool.nodes}",
        f"--ntasks={pool.nodes}",
        "--ntasks-per-node=1",
    ]
    if per_pool_constraint and pool.constraint:
        args.append(f"--constraint={pool.constraint}")
    args.extend([
        "dask", "worker",
        "--scheduler-file", sched_file,
        "--nworkers", str(pool.threads_per_node),
        "--memory-limit", pool.memory,
        "--local-directory", local_dir,
    ])
    if pool.resources:
        args.extend(["--resources", _resources_to_dask_arg(pool.resources)])
    return args


def render_sbatch(spec: ClusterSpec) -> str:
    """Render the sbatch script that brings up the persistent Dask cluster.

    The head node runs ``dask scheduler``; one ``srun`` step per worker pool
    launches ``dask worker``s with their pool-specific ``--resources`` tags
    (and optional per-pool ``--constraint``).  The script holds the
    allocation until the scheduler exits or walltime expires.
    """
    if not spec.account:
        raise ValueError(f"Cluster '{spec.name}': missing 'account'")

    total_nodes = _total_nodes(spec)
    walltime = walltime_to_slurm(spec.walltime)
    scratch = spec.scratch_root
    sched_file = f"{scratch}/lightcone/clusters/{spec.name}.json"
    local_dir = f"{scratch}/lightcone/clusters/scratch"

    lines: list[str] = [
        "#!/bin/bash",
        f"#SBATCH --job-name=lc-cluster-{spec.name}",
        f"#SBATCH --nodes={total_nodes}",
        f"#SBATCH --time={walltime}",
        f"#SBATCH --qos={spec.qos}",
        f"#SBATCH --account={spec.account}",
        f"#SBATCH --output=results/.slurm/lc-cluster-{spec.name}-%j.out",
    ]
    pool_constraints = [w.constraint for w in spec.workers]
    uniform = (
        all(c is not None for c in pool_constraints)
        and len(set(pool_constraints)) == 1
    )
    if uniform:
        lines.append(f"#SBATCH --constraint={pool_constraints[0]}")
        per_pool_constraint = False
    else:
        per_pool_constraint = any(c for c in pool_constraints)

    lines.extend(f"#SBATCH {arg}" for arg in spec.extra_sbatch)
    lines += [
        "",
        "set -euo pipefail",
        "",
        _resolve_worker_init(spec).rstrip(),
        "",
        f'SCHED_FILE="{sched_file}"',
        'mkdir -p "$(dirname "$SCHED_FILE")"',
        "",
        "dask scheduler \\",
        '    --scheduler-file "$SCHED_FILE" \\',
        "    --port 8786 \\",
        "    --dashboard-address :8787 &",
        "SCHED_PID=$!",
        "",
    ]

    for i, pool in enumerate(spec.workers):
        argv = _worker_srun_argv(
            pool, "$SCHED_FILE", local_dir,
            per_pool_constraint=per_pool_constraint,
        )
        rendered = _argv_to_sbatch_line(argv)
        lines.append(f"# pool {i}: {pool.nodes} node(s)" + (
            f", resources={pool.resources}" if pool.resources else ""
        ))
        lines.append(rendered + " &")
        lines.append("")

    lines.append('wait "$SCHED_PID"')
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# QoS preflight
# ---------------------------------------------------------------------------


def _request_from_spec(spec: ClusterSpec) -> dict[str, int | None]:
    return {
        "nodes": _total_nodes(spec),
        "gpus_per_node": max(
            (sum(w.resources.values()) for w in spec.workers), default=0,
        ),
        "time_limit_minutes": parse_walltime_seconds(spec.walltime) // 60,
    }


def _try_clamp_to_fit(
    spec: ClusterSpec,
    qos_info: Any,
    clamped: dict[str, int],
) -> ClusterSpec | None:
    """Apply walltime/nodes clamp from a ``check_qos_eligibility`` result.

    Returns the adjusted spec if it now fits, or ``None`` if clamping
    can't make it fit (e.g. nodes per pool can't be redistributed safely).
    """
    from lightcone.engine.clusters._slurm_info import check_qos_eligibility

    adjusted = spec
    if "time_limit_minutes" in clamped:
        new_minutes = clamped["time_limit_minutes"]
        logger.warning(
            "Reducing cluster '%s' walltime to %d min to fit qos '%s'.",
            spec.name, new_minutes, spec.qos,
        )
        adjusted = _replace(adjusted, walltime=f"{new_minutes}m")
    if "nodes" in clamped:
        # Can't safely re-distribute nodes across user-defined pools — surface
        # to the user; preflight will fall through to "switch".
        logger.warning(
            "Cluster '%s' requests %d nodes; qos '%s' allows %d. "
            "Reduce worker pool sizes manually if you need fewer nodes.",
            spec.name, _total_nodes(spec), spec.qos, clamped["nodes"],
        )
    verify = check_qos_eligibility(qos_info, _request_from_spec(adjusted))
    return adjusted if verify.eligible else None


def _try_switch_qos(
    spec: ClusterSpec,
    cluster: Any,
    request: dict[str, int | None],
    constraint: str | None,
    overrides: dict[str, str],
    site_defaults: dict[str, Any],
) -> ClusterSpec | None:
    """Find an alternative QoS that fits the request, holding constraint fixed."""
    from lightcone.engine.clusters._slurm_info import recommend_qos

    qos_choices = list(
        (site_defaults.get("suggested_options") or {})
        .get("qos", {}).get("choices", {}).keys()
    ) or [spec.qos]
    recs = recommend_qos(
        cluster, request,
        qos_choices=qos_choices, constraint=constraint,
        preferred_qos=spec.qos, cache_key_overrides=overrides,
    )
    best = next((r for r in recs if r.eligible), None)
    return _replace(spec, qos=best.qos) if best else None


def validate_against_qos(spec: ClusterSpec, strategy: str = "fit") -> ClusterSpec:
    """Check the cluster against the cluster cache; adjust or raise.

    ``"fit"``: clamp ``walltime`` and total ``nodes`` to fit the configured
    ``qos`` if exceeded.

    ``"switch"``: pick another QoS from the site-registry-declared choices
    that fits, holding hardware constraint fixed.

    No-ops if the cache is missing or the QoS isn't found in it.
    """
    from lightcone.engine.clusters._slurm_info import check_qos_eligibility

    cluster = load_slurm_cache(spec.site)
    if cluster is None:
        if is_cache_stale(spec.site):
            logger.warning(
                "No SLURM cache for site '%s' — skipping QoS preflight. "
                "Run `lc cluster refresh-cache %s` to enable it.",
                spec.site, spec.site,
            )
        return spec

    site_defaults = SITE_DEFAULTS.get(spec.site, {})
    overrides: dict[str, str] = site_defaults.get("cache_key_overrides", {}) or {}
    constraints = {w.constraint for w in spec.workers if w.constraint}
    constraint = next(iter(constraints)) if len(constraints) == 1 else None

    cache_key = resolve_cache_key(spec.qos, constraint, cluster.qos, overrides)
    qos_info = cluster.qos.get(cache_key)
    if qos_info is None:
        return spec

    request = _request_from_spec(spec)
    current = check_qos_eligibility(qos_info, request)
    if current.eligible:
        return spec

    if strategy == "fit" and current.clamped_resources:
        adjusted = _try_clamp_to_fit(spec, qos_info, current.clamped_resources)
        if adjusted is not None:
            return adjusted

    switched = _try_switch_qos(spec, cluster, request, constraint, overrides, site_defaults)
    if switched is not None:
        logger.warning(
            "qos '%s' cannot host cluster '%s' (%s). Switching to '%s'.",
            spec.qos, spec.name, "; ".join(current.violations), switched.qos,
        )
        return switched

    raise ValueError(
        f"Cluster '{spec.name}' violates qos '{spec.qos}' "
        f"({'; '.join(current.violations)}) and no eligible alternative "
        f"was found. Adjust the cluster config and retry."
    )


def resolve_cache_key(
    qos: str,
    constraint: str | None,
    cache_qos_keys: Any,
    overrides: dict[str, str],
) -> str:
    """Map a ``(qos, constraint)`` to a sacctmgr cache record name."""
    if constraint:
        key = f"{qos}/{constraint}"
        if key in overrides:
            return overrides[key]
    if qos in overrides:
        return overrides[qos]
    if constraint:
        prefixed = f"{constraint}_{qos}"
        if prefixed in cache_qos_keys:
            return prefixed
    return qos


def _replace(spec: ClusterSpec, **changes: Any) -> ClusterSpec:
    """Return a copy of *spec* with *changes* applied."""
    from dataclasses import replace
    return replace(spec, **changes)


# ---------------------------------------------------------------------------
# Worker env auto-bootstrap
# ---------------------------------------------------------------------------


def ensure_worker_env(spec: ClusterSpec) -> Path:
    """Create ``~/.lightcone/envs/<site>/`` with the worker dependencies.

    Idempotent: if the venv's Python exists, returns immediately.
    """
    env = env_path_for_site(spec.site)
    if (env / "bin" / "python").exists():
        return env

    logger.info("Provisioning worker env at %s …", env)
    subprocess.run(["uv", "venv", str(env)], check=True)
    subprocess.run(
        [
            "uv", "pip", "install",
            "--python", str(env / "bin" / "python"),
            "lightcone-cli", "dagster-dask", "distributed",
        ],
        check=True,
    )
    logger.info("Worker env ready: %s", env)
    return env


# ---------------------------------------------------------------------------
# Lifecycle (sbatch / squeue / scancel)
# ---------------------------------------------------------------------------


_SLURM_STATE_MAP = {
    "PD": "PENDING", "PENDING": "PENDING",
    "R": "RUNNING", "RUNNING": "RUNNING",
    "CG": "RUNNING", "COMPLETING": "RUNNING",
    "CD": "COMPLETED", "COMPLETED": "COMPLETED",
    "F": "FAILED", "FAILED": "FAILED",
    "TO": "FAILED", "TIMEOUT": "FAILED", "NF": "FAILED", "NODE_FAIL": "FAILED",
    "CA": "CANCELLED", "CANCELLED": "CANCELLED",
}


def query_slurm_state(job_id: str) -> str:
    """Return one of PENDING/RUNNING/COMPLETED/FAILED/CANCELLED/DEAD."""
    try:
        result = subprocess.run(
            ["squeue", "-h", "-j", job_id, "-o", "%T"],
            capture_output=True, text=True, check=False,
        )
    except FileNotFoundError:
        return "DEAD"
    out = result.stdout.strip()
    if out:
        return _SLURM_STATE_MAP.get(out.split()[0], "RUNNING")
    try:
        result = subprocess.run(
            ["sacct", "-j", job_id, "-o", "State", "-n", "-X", "-P"],
            capture_output=True, text=True, check=False,
        )
    except FileNotFoundError:
        return "DEAD"
    out = result.stdout.strip().splitlines()
    if not out:
        return "DEAD"
    raw = out[0].split()[0].rstrip("+")
    return _SLURM_STATE_MAP.get(raw, "DEAD")


def slurm_cluster_info(name: str, config: dict[str, Any] | None = None) -> ClusterInfo | None:
    """Return spec + record + live SLURM state for the named cluster.

    Dispatches on ``record.mode``: an ``attached`` record yields a
    synthesized spec (no yaml required); a ``sbatch`` record uses the
    yaml as today.  *config* may be passed in by the dispatcher to avoid
    a duplicate ``load_cluster_config`` read on the yaml path.
    """
    record = read_record(name)
    if record is not None and record.mode == "attached":
        spec = _spec_from_attached_record(record)
        state = query_slurm_state(record.job_id)
        address = read_scheduler_address(record.scheduler_file) if state == "RUNNING" else None
        return ClusterInfo(spec=spec, record=record, state=state, scheduler_address=address)

    if config is None:
        config = load_cluster_config(name)
        if config is None:
            return None
    spec = spec_from_config(name, config)
    if record is None:
        return ClusterInfo(spec=spec, record=None, state="NONE", scheduler_address=None)
    state = query_slurm_state(record.job_id)
    address = read_scheduler_address(record.scheduler_file) if state == "RUNNING" else None
    return ClusterInfo(spec=spec, record=record, state=state, scheduler_address=address)


def _spec_from_attached_record(record: ClusterRecord) -> ClusterSpec:
    """Synthesize a display-only :class:`ClusterSpec` for an attached cluster.

    Attached clusters have no yaml — the worker-pool layout was derived
    from SLURM env at attach time.  Most fields are placeholders for
    display purposes (status output, list table); the live SLURM job and
    scheduler address come from the record + live queries.
    """
    site_defaults = SITE_DEFAULTS.get(record.site, {})
    cluster_defaults = (site_defaults.get("slurm") or {})
    scratch_root = cluster_defaults.get("scratch_root") or "$HOME/scratch"
    container_runtime = site_defaults.get("container_runtime") or "podman-hpc"
    return ClusterSpec(
        name=record.name,
        type="slurm",
        site=record.site,
        account="(attached)",
        qos="(attached)",
        walltime=f"{record.walltime_seconds // 60}m" if record.walltime_seconds else "?",
        # Display-only stub; the real worker layout was honoured at attach time.
        workers=[WorkerPool(nodes=1, threads_per_node=1, memory="auto")],
        container_runtime=container_runtime,
        scratch_root=scratch_root,
    )


# ---------------------------------------------------------------------------
# Attach (in-allocation) lifecycle
# ---------------------------------------------------------------------------


def _scratch_root_for_site(site: str) -> str:
    """Return the site's preferred scratch root, expanded for the local FS."""
    cluster_defaults = (SITE_DEFAULTS.get(site, {}).get("slurm") or {})
    return cluster_defaults.get("scratch_root") or "$HOME/scratch"


def attach_to_allocation(
    *,
    project_root: Path | None = None,
) -> ClusterInfo:
    """Spawn a Dask cluster inside the current SLURM allocation.

    Reads SLURM env vars (``SLURM_JOB_ID``, ``SLURM_JOB_NUM_NODES``,
    ``SLURM_CPUS_ON_NODE``) to derive a single uniform worker pool.
    Spawns ``dask scheduler`` on the current node and ``srun … dask
    worker …`` across the allocation.  Both processes are detached
    (``start_new_session=True``) with stdout/stderr redirected to log
    files in ``<project_root>/results/.slurm/``.

    Returns the :class:`ClusterInfo`.  Raises :class:`RuntimeError` if
    not inside a SLURM allocation.
    """
    job_id = os.environ.get("SLURM_JOB_ID")
    if not job_id:
        raise RuntimeError(
            "Not inside a SLURM allocation ($SLURM_JOB_ID is unset). "
            "Use `lc cluster start <name>` to submit a fresh job, or "
            "`salloc` first to grab an interactive allocation."
        )

    name = f"_attached_{job_id}"

    # Idempotent: already-attached for this allocation? Return existing.
    existing = read_record(name)
    if existing is not None:
        info = slurm_cluster_info(name)
        if info and info.state in {"PENDING", "RUNNING"}:
            logger.info("Cluster '%s' already attached (state=%s).", name, info.state)
            return info
        # Stale state from a prior allocation that died — sweep before continuing.
        state_path(name).unlink()
        sched_file = Path(expand_path(existing.scheduler_file))
        if sched_file.exists():
            sched_file.unlink()

    # Sweep dead `_attached_*` records from prior allocations.
    _sweep_dead_attached_records()

    nodes = int(os.environ.get("SLURM_JOB_NUM_NODES", "1"))
    cpus_per_node = int(os.environ.get("SLURM_CPUS_ON_NODE", "0")) or 1
    site = detect_site(socket.gethostname()) or "_attached"
    scratch = expand_path(_scratch_root_for_site(site))

    sched_file_path = f"{scratch}/lightcone/clusters/{name}.json"
    Path(sched_file_path).parent.mkdir(parents=True, exist_ok=True)
    local_dir = f"{scratch}/lightcone/clusters/scratch"
    Path(local_dir).mkdir(parents=True, exist_ok=True)

    pool = WorkerPool(
        nodes=nodes,
        threads_per_node=cpus_per_node,
        memory="auto",
    )

    project_root = project_root or Path.cwd()
    log_dir = project_root / "results" / ".slurm"
    log_dir.mkdir(parents=True, exist_ok=True)

    sched_log = log_dir / f"lc-cluster-{name}-scheduler.log"
    worker_log = log_dir / f"lc-cluster-{name}-workers.log"

    sched_argv = [
        "dask", "scheduler",
        "--scheduler-file", sched_file_path,
        "--port", "8786",
        "--dashboard-address", ":8787",
    ]
    sched_proc = subprocess.Popen(
        sched_argv,
        stdout=open(sched_log, "w"),
        stderr=subprocess.STDOUT,
        start_new_session=True,
        cwd=str(project_root),
    )

    worker_argv = _worker_srun_argv(pool, sched_file_path, local_dir)
    worker_proc = subprocess.Popen(
        worker_argv,
        stdout=open(worker_log, "w"),
        stderr=subprocess.STDOUT,
        start_new_session=True,
        cwd=str(project_root),
    )

    walltime_seconds = _slurm_walltime_seconds_from_env()

    record = ClusterRecord(
        name=name,
        type="slurm",
        job_id=job_id,
        site=site,
        submitted_at=datetime.now(UTC).isoformat(),
        walltime_seconds=walltime_seconds,
        scheduler_file=sched_file_path,
        mode="attached",
        process_pids=[sched_proc.pid, worker_proc.pid],
    )
    write_record(record)
    logger.info(
        "Attached cluster '%s' to allocation %s (%d nodes, %d cpus/node).",
        name, job_id, nodes, cpus_per_node,
    )

    spec = _spec_from_attached_record(record)
    return ClusterInfo(spec=spec, record=record, state="PENDING", scheduler_address=None)


def _slurm_walltime_seconds_from_env() -> int:
    """Best-effort walltime for the current allocation, in seconds."""
    # SLURM doesn't expose time-remaining directly via env; SLURM_TIMELIMIT
    # carries the requested limit in minutes when set. Fall back to 0 if
    # absent (display-only — record is informational for attached mode).
    raw = os.environ.get("SLURM_TIMELIMIT") or "0"
    try:
        return int(raw) * 60
    except ValueError:
        return 0


def _sweep_dead_attached_records() -> None:
    """Remove ``_attached_*`` state files whose SLURM jobs are no longer alive."""
    from lightcone.engine.clusters._common import list_state_records

    for record in list_state_records():
        if record.mode != "attached":
            continue
        if query_slurm_state(record.job_id) in {"DEAD", "COMPLETED", "FAILED", "CANCELLED"}:
            try:
                state_path(record.name).unlink()
            except FileNotFoundError:
                pass
            sched_file = Path(expand_path(record.scheduler_file))
            if sched_file.exists():
                try:
                    sched_file.unlink()
                except OSError:
                    pass


def start_slurm_cluster(
    name: str,
    config: dict[str, Any],
    overrides: dict[str, Any],
    *,
    project_root: Path | None = None,
    strategy: str = "fit",
) -> ClusterInfo:
    """Submit the SLURM allocation and record state."""
    if overrides:
        for k, v in overrides.items():
            if v is not None:
                config[k] = v

    existing_record = read_record(name)
    if existing_record is not None:
        existing = slurm_cluster_info(name, config=config)
        if existing and existing.state in {"PENDING", "RUNNING"}:
            # Idempotent: cluster already up. Caller treats this as success.
            logger.info(
                "Cluster '%s' already running (job %s, state=%s).",
                name, existing_record.job_id, existing.state,
            )
            return existing
        # Stale state file (recorded job is dead) — sweep and proceed.
        state_path(name).unlink()
        sched_file = Path(expand_path(existing_record.scheduler_file))
        if sched_file.exists():
            sched_file.unlink()

    spec = spec_from_config(name, config)
    spec = validate_against_qos(spec, strategy=strategy)
    ensure_worker_env(spec)

    script = render_sbatch(spec)
    project_root = project_root or Path.cwd()
    scripts_dir = project_root / "results" / ".slurm"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    script_path = scripts_dir / f"lc-cluster-{name}.sbatch"
    script_path.write_text(script)
    script_path.chmod(0o755)

    submit = subprocess.run(
        ["sbatch", str(script_path)],
        capture_output=True, text=True, cwd=str(project_root),
    )
    if submit.returncode != 0:
        raise RuntimeError(f"sbatch failed: {submit.stderr.strip() or submit.stdout.strip()}")

    job_id = parse_job_id(submit.stdout)
    if job_id is None:
        raise RuntimeError(f"could not parse job id from sbatch output: {submit.stdout!r}")

    record = ClusterRecord(
        name=name,
        type="slurm",
        job_id=job_id,
        site=spec.site,
        submitted_at=datetime.now(UTC).isoformat(),
        walltime_seconds=parse_walltime_seconds(spec.walltime),
        scheduler_file=f"{spec.scratch_root}/lightcone/clusters/{name}.json",
    )
    write_record(record)
    logger.info("Cluster '%s' submitted as SLURM job %s", name, job_id)
    return ClusterInfo(spec=spec, record=record, state="PENDING", scheduler_address=None)


def stop_slurm_cluster(name: str) -> None:
    """Tear down a SLURM-backed cluster.

    Mode-aware: ``sbatch`` clusters get ``scancel``-ed (we own the job);
    ``attached`` clusters get the dask scheduler/workers killed by PID,
    leaving the user's allocation intact.  Both paths clean up the
    scheduler-file and state file.
    """
    record = read_record(name)
    if record is None:
        logger.info("No active state for cluster '%s' — nothing to stop.", name)
        return
    if record.mode == "attached":
        for pid in record.process_pids:
            try:
                os.kill(pid, signal.SIGTERM)
            except ProcessLookupError:
                pass
            except PermissionError:
                logger.warning(
                    "No permission to kill pid %d for cluster '%s'.", pid, name,
                )
        logger.info(
            "Cluster '%s' stopped (killed dask processes; allocation %s untouched)",
            name, record.job_id,
        )
    else:
        subprocess.run(["scancel", record.job_id], check=False)
        logger.info("Cluster '%s' stopped (cancelled SLURM job %s)", name, record.job_id)
    sched_file = Path(expand_path(record.scheduler_file))
    if sched_file.exists():
        sched_file.unlink()
    state_path(name).unlink()


def tail_slurm_logs(
    name: str,
    project_root: Path | None = None,
    follow: bool = False,
    lines: int = 200,
) -> None:
    """Stream the SLURM stdout file for a cluster."""
    record = read_record(name)
    if record is None:
        raise RuntimeError(f"No active state for cluster '{name}'")
    project_root = project_root or Path.cwd()
    log_path = project_root / "results" / ".slurm" / f"lc-cluster-{name}-{record.job_id}.out"
    if not log_path.exists():
        raise FileNotFoundError(f"Log file not found: {log_path}")
    cmd = ["tail", f"-n{lines}"]
    if follow:
        cmd.append("-f")
    cmd.append(str(log_path))
    subprocess.run(cmd, check=False)


def parse_job_id(sbatch_stdout: str) -> str | None:
    """Extract the job id from ``Submitted batch job 12345``."""
    for line in sbatch_stdout.splitlines():
        parts = line.split()
        if parts and parts[-1].isdigit():
            return parts[-1]
    return None
