"""SLURM substrate for the cluster abstraction.

Owns everything SLURM-specific: sbatch rendering, ``sbatch``/``squeue``/
``scancel`` lifecycle, QoS preflight against the cluster cache, and
``uv`` worker-env bootstrap.  Public entrypoints take a name + config and
return the same :class:`ClusterInfo` shape every other substrate would.

Future ``_k8s.py`` mirrors this surface.
"""
from __future__ import annotations

import logging
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from lightcone.engine.clusters._common import (
    ClusterInfo,
    ClusterSpec,
    ClusterState,
    env_path_for_site,
    expand_path,
    get_cache_dir,
    list_clusters,
    load_cluster_config,
    parse_walltime_seconds,
    read_scheduler_address,
    read_state,
    spec_from_config,
    state_path,
    walltime_to_slurm,
    write_state,
)
from lightcone.engine.site_registry import SITE_DEFAULTS

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Site-keyed SLURM cluster discovery cache (sacctmgr / scontrol output)
# ---------------------------------------------------------------------------


def _cache_path(site: str) -> Path:
    return get_cache_dir() / f"{site}.slurm.yaml"


def load_slurm_cache(site: str) -> Any:
    """Load cached SLURM cluster info (sacctmgr/scontrol) for *site* or ``None``."""
    from lightcone.engine.clusters._slurm_info import cluster_info_from_dict

    path = _cache_path(site)
    if not path.exists():
        return None
    with open(path) as f:
        data = yaml.safe_load(f)
    return cluster_info_from_dict(data) if data else None


def save_slurm_cache(site: str, info: Any) -> Path:
    from lightcone.engine.clusters._slurm_info import cluster_info_to_dict

    path = _cache_path(site)
    with open(path, "w") as f:
        f.write("# AUTO-GENERATED by `lc cluster refresh-cache`. Do not edit.\n")
        yaml.dump(cluster_info_to_dict(info), f, default_flow_style=False, sort_keys=False)
    return path


def is_cache_stale(site: str, max_age_days: int = 30) -> bool:
    path = _cache_path(site)
    if not path.exists():
        return True
    with open(path) as f:
        data = yaml.safe_load(f)
    if not data or not data.get("timestamp"):
        return True
    try:
        ts = datetime.fromisoformat(data["timestamp"])
        return (datetime.now(UTC) - ts).days > max_age_days
    except (ValueError, TypeError):
        return True


def refresh_slurm_cache(site: str) -> Any:
    """Re-query SLURM (sacctmgr/scontrol) and rewrite the cache for *site*."""
    from lightcone.engine.clusters._slurm_info import discover_cluster

    info = discover_cluster()
    save_slurm_cache(site, info)
    return info


# ---------------------------------------------------------------------------
# Sbatch rendering
# ---------------------------------------------------------------------------


def _resolve_worker_init(spec: ClusterSpec) -> str:
    """Return the bash snippet that activates the worker env on compute nodes."""
    if spec.worker_init:
        return spec.worker_init.rstrip() + "\n"
    site_defaults = SITE_DEFAULTS.get(spec.site, {})
    template = (site_defaults.get("cluster") or {}).get("worker_init_template")
    if template:
        return template.rstrip() + "\n"
    return f"source $HOME/.lightcone/envs/{spec.site}/bin/activate\n"


def _resources_to_dask_arg(resources: dict[str, int]) -> str:
    """Translate ``{"GPU": 4}`` → ``"GPU=4"`` for ``dask worker --resources``."""
    return ",".join(f"{k}={v}" for k, v in sorted(resources.items()))


def _total_nodes(spec: ClusterSpec) -> int:
    return sum(w.nodes for w in spec.workers)


def render_sbatch(spec: ClusterSpec) -> str:
    """Render the sbatch script that brings up the persistent Dask cluster.

    The head node runs ``dask scheduler``; one ``srun`` step per worker pool
    launches ``dask worker``s with their pool-specific ``--resources`` tags
    (and optional per-pool ``--constraint``).  The script holds the
    allocation until the scheduler exits or walltime expires.
    """
    if not spec.account:
        raise ValueError(f"Cluster '{spec.name}': missing 'account'")

    total_nodes = _total_nodes(spec)
    walltime = walltime_to_slurm(spec.walltime)
    scratch = spec.scratch_root
    sched_file = f"{scratch}/lightcone/clusters/{spec.name}.json"
    local_dir = f"{scratch}/lightcone/clusters/scratch"

    lines: list[str] = [
        "#!/bin/bash",
        f"#SBATCH --job-name=lc-cluster-{spec.name}",
        f"#SBATCH --nodes={total_nodes}",
        f"#SBATCH --time={walltime}",
        f"#SBATCH --qos={spec.qos}",
        f"#SBATCH --account={spec.account}",
        f"#SBATCH --output=results/.slurm/lc-cluster-{spec.name}-%j.out",
    ]
    pool_constraints = [w.constraint for w in spec.workers]
    uniform = (
        all(c is not None for c in pool_constraints)
        and len(set(pool_constraints)) == 1
    )
    if uniform:
        lines.append(f"#SBATCH --constraint={pool_constraints[0]}")
        per_pool_constraint = False
    else:
        per_pool_constraint = any(c for c in pool_constraints)

    lines.extend(f"#SBATCH {arg}" for arg in spec.extra_sbatch)
    lines += [
        "",
        "set -euo pipefail",
        "",
        _resolve_worker_init(spec).rstrip(),
        "",
        f'SCHED_FILE="{sched_file}"',
        'mkdir -p "$(dirname "$SCHED_FILE")"',
        "",
        "dask scheduler \\",
        '    --scheduler-file "$SCHED_FILE" \\',
        "    --port 8786 \\",
        "    --dashboard-address :8787 &",
        "SCHED_PID=$!",
        "",
    ]

    for i, pool in enumerate(spec.workers):
        srun_parts = [
            "srun",
            f"--nodes={pool.nodes}",
            f"--ntasks={pool.nodes}",
            "--ntasks-per-node=1",
        ]
        if per_pool_constraint and pool.constraint:
            srun_parts.append(f"--constraint={pool.constraint}")
        srun_parts.append("dask worker")
        srun_parts.append('--scheduler-file "$SCHED_FILE"')
        srun_parts.append(f"--nworkers {pool.threads_per_node}")
        srun_parts.append(f'--memory-limit "{pool.memory}"')
        srun_parts.append(f'--local-directory "{local_dir}"')
        if pool.resources:
            srun_parts.append(f'--resources "{_resources_to_dask_arg(pool.resources)}"')
        rendered = " \\\n     ".join(srun_parts)
        lines.append(f"# pool {i}: {pool.nodes} node(s)" + (
            f", resources={pool.resources}" if pool.resources else ""
        ))
        lines.append(rendered + " &")
        lines.append("")

    lines.append('wait "$SCHED_PID"')
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# QoS preflight (port of runner._validate_and_adjust_qos)
# ---------------------------------------------------------------------------


def validate_against_qos(spec: ClusterSpec, strategy: str = "fit") -> ClusterSpec:
    """Check the cluster against the cluster cache; adjust or raise.

    ``"fit"``: clamp ``walltime`` and total ``nodes`` to fit the configured
    ``qos`` if exceeded.

    ``"switch"``: pick another QoS from the site-registry-declared choices
    that fits, holding hardware constraint fixed.

    Returns a (possibly adjusted) :class:`ClusterSpec`.  No-ops if the cache
    is missing or the QoS isn't found in it.
    """
    from lightcone.engine.clusters._slurm_info import (
        check_qos_eligibility,
        recommend_qos,
    )

    cluster = load_slurm_cache(spec.site)
    if cluster is None:
        if is_cache_stale(spec.site):
            logger.warning(
                "No SLURM cache for site '%s' — skipping QoS preflight. "
                "Run `lc cluster refresh-cache %s` to enable it.",
                spec.site, spec.site,
            )
        return spec

    site_defaults = SITE_DEFAULTS.get(spec.site, {})
    overrides: dict[str, str] = site_defaults.get("cache_key_overrides", {}) or {}
    constraints = {w.constraint for w in spec.workers if w.constraint}
    constraint = next(iter(constraints)) if len(constraints) == 1 else None

    cache_key = resolve_cache_key(spec.qos, constraint, cluster.qos, overrides)
    qos_info = cluster.qos.get(cache_key)
    if qos_info is None:
        return spec

    nodes_total = _total_nodes(spec)
    gpus_per_node = max((sum(w.resources.values()) for w in spec.workers), default=0)
    walltime_minutes = parse_walltime_seconds(spec.walltime) // 60

    request = {
        "nodes": nodes_total,
        "gpus_per_node": gpus_per_node,
        "time_limit_minutes": walltime_minutes,
    }
    current = check_qos_eligibility(qos_info, request)
    if current.eligible:
        return spec

    if strategy == "fit" and current.clamped_resources:
        clamped = current.clamped_resources
        adjusted = spec
        if "time_limit_minutes" in clamped:
            new_minutes = clamped["time_limit_minutes"]
            logger.warning(
                "Reducing cluster '%s' walltime to %d min to fit qos '%s'.",
                spec.name, new_minutes, spec.qos,
            )
            adjusted = _replace(adjusted, walltime=f"{new_minutes}m")
        if "nodes" in clamped:
            new_nodes = clamped["nodes"]
            logger.warning(
                "Cluster '%s' requests %d nodes; qos '%s' allows %d. "
                "Reduce the worker pool sizes manually if you need fewer nodes.",
                spec.name, nodes_total, spec.qos, new_nodes,
            )
        verify = check_qos_eligibility(qos_info, {
            "nodes": _total_nodes(adjusted),
            "gpus_per_node": gpus_per_node,
            "time_limit_minutes": parse_walltime_seconds(adjusted.walltime) // 60,
        })
        if verify.eligible:
            return adjusted

    qos_choices = list((site_defaults.get("suggested_options") or {})
                       .get("qos", {}).get("choices", {}).keys()) or [spec.qos]
    recs = recommend_qos(
        cluster, request,
        qos_choices=qos_choices, constraint=constraint,
        preferred_qos=spec.qos, cache_key_overrides=overrides,
    )
    best = next((r for r in recs if r.eligible), None)
    if best:
        logger.warning(
            "qos '%s' cannot host cluster '%s' (%s). Switching to '%s'.",
            spec.qos, spec.name, "; ".join(current.violations), best.qos,
        )
        return _replace(spec, qos=best.qos)

    raise ValueError(
        f"Cluster '{spec.name}' violates qos '{spec.qos}' "
        f"({'; '.join(current.violations)}) and no eligible alternative "
        f"was found. Adjust the cluster config and retry."
    )


def resolve_cache_key(
    qos: str,
    constraint: str | None,
    cache_qos_keys: Any,
    overrides: dict[str, str],
) -> str:
    """Map a ``(qos, constraint)`` to a sacctmgr cache record name."""
    if constraint:
        key = f"{qos}/{constraint}"
        if key in overrides:
            return overrides[key]
    if qos in overrides:
        return overrides[qos]
    if constraint:
        prefixed = f"{constraint}_{qos}"
        if prefixed in cache_qos_keys:
            return prefixed
    return qos


def _replace(spec: ClusterSpec, **changes: Any) -> ClusterSpec:
    """Return a copy of *spec* with *changes* applied."""
    from dataclasses import replace
    return replace(spec, **changes)


# ---------------------------------------------------------------------------
# Worker env auto-bootstrap
# ---------------------------------------------------------------------------


def ensure_worker_env(spec: ClusterSpec) -> Path:
    """Create ``~/.lightcone/envs/<site>/`` with the worker dependencies.

    Idempotent: if the venv's Python exists, returns immediately.
    """
    env = env_path_for_site(spec.site)
    if (env / "bin" / "python").exists():
        return env

    logger.info("Provisioning worker env at %s …", env)
    subprocess.run(["uv", "venv", str(env)], check=True)
    subprocess.run(
        [
            "uv", "pip", "install",
            "--python", str(env / "bin" / "python"),
            "lightcone-cli", "dagster-dask", "distributed",
        ],
        check=True,
    )
    logger.info("Worker env ready: %s", env)
    return env


# ---------------------------------------------------------------------------
# Lifecycle (sbatch / squeue / scancel)
# ---------------------------------------------------------------------------


_SLURM_STATE_MAP = {
    "PD": "PENDING", "PENDING": "PENDING",
    "R": "RUNNING", "RUNNING": "RUNNING",
    "CG": "RUNNING", "COMPLETING": "RUNNING",
    "CD": "COMPLETED", "COMPLETED": "COMPLETED",
    "F": "FAILED", "FAILED": "FAILED",
    "TO": "FAILED", "TIMEOUT": "FAILED", "NF": "FAILED", "NODE_FAIL": "FAILED",
    "CA": "CANCELLED", "CANCELLED": "CANCELLED",
}


def query_slurm_state(job_id: str) -> str:
    """Return one of PENDING/RUNNING/COMPLETED/FAILED/CANCELLED/DEAD."""
    try:
        result = subprocess.run(
            ["squeue", "-h", "-j", job_id, "-o", "%T"],
            capture_output=True, text=True, check=False,
        )
    except FileNotFoundError:
        return "DEAD"
    out = result.stdout.strip()
    if out:
        return _SLURM_STATE_MAP.get(out.split()[0], "RUNNING")
    try:
        result = subprocess.run(
            ["sacct", "-j", job_id, "-o", "State", "-n", "-X", "-P"],
            capture_output=True, text=True, check=False,
        )
    except FileNotFoundError:
        return "DEAD"
    out = result.stdout.strip().splitlines()
    if not out:
        return "DEAD"
    raw = out[0].split()[0].rstrip("+")
    return _SLURM_STATE_MAP.get(raw, "DEAD")


def slurm_cluster_info(name: str) -> ClusterInfo | None:
    """Return spec + state + live SLURM state for the named cluster."""
    config = load_cluster_config(name)
    if config is None:
        return None
    spec = spec_from_config(name, config)
    state = read_state(name)
    if state is None:
        return ClusterInfo(spec=spec, state=None, slurm_state="NONE", scheduler_address=None)
    slurm_state = query_slurm_state(state.job_id)
    address = read_scheduler_address(state.scheduler_file) if slurm_state == "RUNNING" else None
    return ClusterInfo(spec=spec, state=state, slurm_state=slurm_state, scheduler_address=address)


def start_slurm_cluster(
    name: str,
    config: dict[str, Any],
    overrides: dict[str, Any],
    *,
    project_root: Path | None = None,
    strategy: str = "fit",
) -> ClusterInfo:
    """Submit the SLURM allocation and record state."""
    if overrides:
        for k, v in overrides.items():
            if v is not None:
                config[k] = v

    if read_state(name) is not None:
        existing = slurm_cluster_info(name)
        if existing and existing.state and existing.slurm_state in {"PENDING", "RUNNING"}:
            raise RuntimeError(
                f"Cluster '{name}' already has an active job ({existing.state.job_id}, "
                f"state={existing.slurm_state}). Run `lc cluster stop {name}` first."
            )
        state_path(name).unlink()

    spec = spec_from_config(name, config)
    spec = validate_against_qos(spec, strategy=strategy)
    ensure_worker_env(spec)

    script = render_sbatch(spec)
    project_root = project_root or Path.cwd()
    scripts_dir = project_root / "results" / ".slurm"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    script_path = scripts_dir / f"lc-cluster-{name}.sbatch"
    script_path.write_text(script)
    script_path.chmod(0o755)

    submit = subprocess.run(
        ["sbatch", str(script_path)],
        capture_output=True, text=True, cwd=str(project_root),
    )
    if submit.returncode != 0:
        raise RuntimeError(f"sbatch failed: {submit.stderr.strip() or submit.stdout.strip()}")

    job_id = parse_job_id(submit.stdout)
    if job_id is None:
        raise RuntimeError(f"could not parse job id from sbatch output: {submit.stdout!r}")

    state = ClusterState(
        name=name,
        type="slurm",
        job_id=job_id,
        site=spec.site,
        submitted_at=datetime.now(UTC).isoformat(),
        walltime_seconds=parse_walltime_seconds(spec.walltime),
        scheduler_file=f"{spec.scratch_root}/lightcone/clusters/{name}.json",
    )
    write_state(state)
    logger.info("Cluster '%s' submitted as SLURM job %s", name, job_id)
    return ClusterInfo(spec=spec, state=state, slurm_state="PENDING", scheduler_address=None)


def stop_slurm_cluster(name: str) -> None:
    """``scancel`` the job and remove the state file (and stale scheduler-file)."""
    state = read_state(name)
    if state is None:
        logger.info("No active state for cluster '%s' — nothing to stop.", name)
        return
    subprocess.run(["scancel", state.job_id], check=False)
    sched_file = Path(expand_path(state.scheduler_file))
    if sched_file.exists():
        sched_file.unlink()
    state_path(name).unlink()
    logger.info("Cluster '%s' stopped (cancelled SLURM job %s)", name, state.job_id)


def tail_slurm_logs(
    name: str,
    project_root: Path | None = None,
    follow: bool = False,
    lines: int = 200,
) -> None:
    """Stream the SLURM stdout file for a cluster."""
    state = read_state(name)
    if state is None:
        raise RuntimeError(f"No active state for cluster '{name}'")
    project_root = project_root or Path.cwd()
    log_path = project_root / "results" / ".slurm" / f"lc-cluster-{name}-{state.job_id}.out"
    if not log_path.exists():
        raise FileNotFoundError(f"Log file not found: {log_path}")
    cmd = ["tail", f"-n{lines}"]
    if follow:
        cmd.append("-f")
    cmd.append(str(log_path))
    subprocess.run(cmd, check=False)


def parse_job_id(sbatch_stdout: str) -> str | None:
    """Extract the job id from ``Submitted batch job 12345``."""
    for line in sbatch_stdout.splitlines():
        parts = line.split()
        if parts and parts[-1].isdigit():
            return parts[-1]
    return None


# Silence unused-import warning for `list_clusters`; it's part of the
# public namespace exported via `__init__.py`.
_ = list_clusters
