# generated by lightcone-cli — DO NOT EDIT
# (rendered from pyproject.toml [tool.lightcone.image]; regenerated by `lc build`)
FROM docker.io/library/debian:bookworm-slim@sha256:abd67ffcfa541b485a3dff59865ab629aa048a6c613e639d36e7456b0b229241 AS env
SHELL ["/bin/sh", "-c"]

# base contract checks — each failure is a distinct exit code the
# builder maps to a pointed error (never a raw build log)
RUN test -x /bin/sh || exit 41
RUN if ls /lib/ld-musl-* >/dev/null 2>&1; then echo 'musl base' >&2; exit 43; fi
RUN command -v apt-get >/dev/null 2>&1 || exit 44

# system layer — installed BEFORE uv sync so lock-level system
# dependencies (sdist builds, rpy2-style imports) resolve here
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       r-base-core \
    && rm -rf /var/lib/apt/lists/*

# pinned uv binary (manifest-list digest — arch-independent text)
COPY --from=ghcr.io/astral-sh/uv@sha256:2d890623d310b57771ce840f0da5eed5fc6d657da05ffaa45d82797b53fa3abc /uv /opt/lc/bin/uv

# exact interpreter, uv-managed, outside the base's control
ENV UV_PYTHON_INSTALL_DIR=/opt/python
RUN /opt/lc/bin/uv python install 3.12.12

# locked sync — code-free: pyproject.toml + uv.lock are the only
# project files that ever enter an image (G5)
WORKDIR /opt/lc/project
COPY pyproject.toml uv.lock ./
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
RUN /opt/lc/bin/uv sync --locked --exact --no-install-project --compile-bytecode --python 3.12.12 --project /opt/lc/project

# user extra stage (Containerfile.extra, verbatim)
FROM env AS extra
RUN Rscript -e 'install.packages("cmdstanr")'

FROM extra AS final
LABEL io.lightcone.env-version="sha256:abababababababababababababababababababababababababababababababab"
# attestation: name-pinned apt layer's actual package versions
RUN dpkg -l > /opt/lc/dpkg-snapshot.txt 2>/dev/null || echo 'dpkg unavailable' > /opt/lc/dpkg-snapshot.txt
RUN printf '%s' '{"env_version":"sha256:abababababababababababababababababababababababababababababababab","python_version":"3.12.12","uv_version":"0.12.3"}' > /opt/lc/identity.json
# world-readable: the invoking uid (rootless --userns=keep-id)
# must be able to read everything lc baked
RUN chmod -R a+rX /opt/lc /opt/python /opt/venv
# offline overlay — FINAL stage only; earlier stages keep network
ENV UV_OFFLINE=1 UV_PYTHON_DOWNLOADS=never UV_NO_SYNC=1 \
    UV_PROJECT_ENVIRONMENT=/opt/venv \
    UV_PYTHON_INSTALL_DIR=/opt/python \
    PATH=/opt/venv/bin:/opt/lc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
