"""Target configuration management for Dagster execution backends."""
from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------


def get_targets_dir() -> Path:
    """Return the user-level targets directory (~/.prism/targets/)."""
    return Path.home() / ".prism" / "targets"


def get_cache_dir() -> Path:
    """Return the cluster cache directory (~/.prism/cache/)."""
    cache = Path.home() / ".prism" / "cache"
    cache.mkdir(parents=True, exist_ok=True)
    return cache


# ---------------------------------------------------------------------------
# Target CRUD (unchanged public API)
# ---------------------------------------------------------------------------


def list_targets() -> list[str]:
    """Return names of saved target configurations."""
    targets_dir = get_targets_dir()
    if not targets_dir.exists():
        return []
    return sorted(p.stem for p in targets_dir.glob("*.yaml"))


def load_target(name: str) -> dict[str, Any] | None:
    """Load a saved target configuration by name.

    Auto-migrates old-format targets to the new schema and rewrites the
    file so the migration happens only once.  Returns ``None`` if the
    target does not exist.
    """
    config_path = get_targets_dir() / f"{name}.yaml"
    if not config_path.exists():
        return None
    with open(config_path) as f:
        config = yaml.safe_load(f)
    if config and _is_old_format(config):
        config = migrate_target(config)
        save_target(name, config)
    return config


def save_target(name: str, config: dict[str, Any]) -> Path:
    """Save a target configuration to ~/.prism/targets/{name}.yaml."""
    targets_dir = get_targets_dir()
    targets_dir.mkdir(parents=True, exist_ok=True)
    config_path = targets_dir / f"{name}.yaml"
    with open(config_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)
    return config_path


# ---------------------------------------------------------------------------
# User config (unchanged)
# ---------------------------------------------------------------------------


def get_config_path() -> Path:
    """Return the user-level config file path (~/.prism/config.yaml)."""
    return Path.home() / ".prism" / "config.yaml"


def load_user_config() -> dict[str, Any]:
    """Load the user-level Prism configuration.

    Returns an empty dict if the config file doesn't exist.
    """
    config_path = get_config_path()
    if not config_path.exists():
        return {}
    with open(config_path) as f:
        return yaml.safe_load(f) or {}


def save_user_config(config: dict[str, Any]) -> Path:
    """Save user-level Prism configuration to ~/.prism/config.yaml.

    Returns the path where it was saved.
    """
    config_path = get_config_path()
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)
    return config_path


# ---------------------------------------------------------------------------
# Cluster cache management
# ---------------------------------------------------------------------------


def load_cluster_cache(target_name: str) -> Any:
    """Load cached ``ClusterInfo`` for a target.

    Returns ``None`` if no cache file exists.
    """
    from prism.dagster.slurm_info import cluster_info_from_dict

    cache_path = get_cache_dir() / f"{target_name}.cluster.yaml"
    if not cache_path.exists():
        return None
    with open(cache_path) as f:
        data = yaml.safe_load(f)
    if not data:
        return None
    return cluster_info_from_dict(data)


def save_cluster_cache(target_name: str, info: Any) -> Path:
    """Write ``ClusterInfo`` to the cache directory."""
    from prism.dagster.slurm_info import cluster_info_to_dict

    cache_path = get_cache_dir() / f"{target_name}.cluster.yaml"
    data = cluster_info_to_dict(info)
    with open(cache_path, "w") as f:
        f.write("# AUTO-GENERATED by `prism target refresh`. Do not edit.\n")
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)
    return cache_path


def is_cache_stale(target_name: str, max_age_days: int = 30) -> bool:
    """Return True if cache doesn't exist or is older than *max_age_days*."""
    cache_path = get_cache_dir() / f"{target_name}.cluster.yaml"
    if not cache_path.exists():
        return True
    with open(cache_path) as f:
        data = yaml.safe_load(f)
    if not data or not data.get("timestamp"):
        return True
    try:
        ts = datetime.fromisoformat(data["timestamp"])
        age = datetime.now(UTC) - ts
        return age.days > max_age_days
    except (ValueError, TypeError):
        return True


def refresh_cluster_cache(target_name: str) -> Any:
    """Re-query SLURM and update the cache for *target_name*."""
    from prism.dagster.slurm_info import discover_cluster

    info = discover_cluster()
    save_cluster_cache(target_name, info)
    return info


# ---------------------------------------------------------------------------
# Schema migration
# ---------------------------------------------------------------------------

_OLD_FLAT_KEYS = {"qos", "constraint", "max_nodes",
                  "max_walltime_minutes", "max_concurrent_jobs"}


def _is_old_format(config: dict[str, Any]) -> bool:
    """Return True if the target uses the old flat schema."""
    return "defaults" not in config and bool(_OLD_FLAT_KEYS & set(config))


def migrate_target(config: dict[str, Any]) -> dict[str, Any]:
    """Migrate an old-format target to the new schema.

    Old format::

        qos: debug
        constraint: gpu
        max_nodes: 4
        container_flags: ["--gpu"]

    New format::

        defaults:
          qos: debug
          constraint: gpu
        qos:
          - name: debug
            constraint: gpu
            use_for: default
        resource_limits:
          max_nodes: 4
    """
    drop = {"qos", "constraint", "max_nodes", "max_walltime_minutes",
            "max_concurrent_jobs", "container_flags", "node_type"}
    new: dict[str, Any] = {k: v for k, v in config.items() if k not in drop}

    # defaults
    defaults: dict[str, Any] = {}
    if "qos" in config:
        defaults["qos"] = config["qos"]
    if "constraint" in config:
        defaults["constraint"] = config["constraint"]
    if defaults:
        new["defaults"] = defaults

    # qos list
    if "qos" in config:
        from prism.dagster.slurm_info import infer_qos_constraint
        qos_name = config["qos"]
        constraint = config.get("constraint") or infer_qos_constraint(qos_name)
        new["qos"] = [{"name": qos_name, "constraint": constraint,
                        "use_for": "default"}]

    # resource_limits
    limits: dict[str, Any] = {}
    for key in ("max_nodes", "max_walltime_minutes", "max_concurrent_jobs"):
        if key in config:
            limits[key] = config[key]
    if limits:
        new["resource_limits"] = limits

    return new


# ---------------------------------------------------------------------------
# Run config resolution
# ---------------------------------------------------------------------------


def resolve_run_config(
    target_config: dict[str, Any],
    cli_overrides: dict[str, Any],
) -> dict[str, Any]:
    """Merge CLI overrides with target defaults.

    Resolution order: ``cli_override > target default > None``.

    For non-SLURM backends (local, docker, venv), returns an empty dict
    and warns if SLURM-specific overrides were passed.
    """
    backend = target_config.get("backend", "local")
    slurm_keys = {"qos", "constraint", "partition"}

    if backend != "slurm":
        used = slurm_keys & set(cli_overrides)
        if used:
            for key in used:
                logger.warning(
                    "--%s is ignored for %s backend (no scheduler).", key, backend,
                )
        return {}

    defaults = target_config.get("defaults") or {}
    result: dict[str, Any] = {}
    for key in ("qos", "constraint", "time_limit", "account", "partition"):
        val = cli_overrides.get(key) or defaults.get(key)
        if val is not None:
            result[key] = val

    # Validate qos against target's allowed list (by name)
    allowed = get_allowed_qos_names(target_config)
    chosen_qos = result.get("qos")
    if allowed and chosen_qos and chosen_qos not in allowed:
        raise ValueError(
            f"'{chosen_qos}' is not in this target's qos list: {allowed}. "
            "Edit the target to add it."
        )

    # Auto-set constraint from qos entry if not explicitly overridden
    if "constraint" not in cli_overrides and chosen_qos:
        entry = get_qos_entry(target_config, chosen_qos)
        if entry and entry.get("constraint"):
            result["constraint"] = entry["constraint"]

    # Translate qos name to slurm_qos (what gets passed to --qos=)
    if chosen_qos:
        entry = get_qos_entry(
            target_config, chosen_qos, result.get("constraint"),
        )
        if entry:
            slurm_qos = entry.get("slurm_qos")
            if slurm_qos:
                result["qos"] = slurm_qos

    return result


# ---------------------------------------------------------------------------
# QoS query helpers
# ---------------------------------------------------------------------------


def get_qos_entries(target_config: dict[str, Any]) -> list[dict[str, Any]]:
    """Return the target's ``qos`` list."""
    return target_config.get("qos") or []


def get_allowed_qos_names(target_config: dict[str, Any]) -> list[str]:
    """Extract QoS names from the target's ``qos`` list.

    May contain duplicates when the same QoS appears with different
    constraints (e.g., ``debug`` for both GPU and CPU).
    """
    return [e["name"] for e in get_qos_entries(target_config) if "name" in e]


def get_qos_entry(
    target_config: dict[str, Any],
    qos_name: str,
    constraint: str | None = None,
) -> dict[str, Any] | None:
    """Return the qos entry matching *qos_name* and optionally *constraint*.

    When the same QoS name appears with multiple constraints (e.g.,
    ``debug`` for GPU and CPU), pass *constraint* to disambiguate.
    Without *constraint*, returns the first match.
    """
    for entry in get_qos_entries(target_config):
        if entry.get("name") != qos_name:
            continue
        if constraint is None or entry.get("constraint") == constraint:
            return entry
    return None


def filter_qos_by_hardware(
    target_config: dict[str, Any],
    needs_gpu: bool,
) -> list[dict[str, Any]]:
    """Return qos entries matching the hardware requirement."""
    result = []
    for entry in get_qos_entries(target_config):
        c = entry.get("constraint", "")
        if needs_gpu and "gpu" in c:
            result.append(entry)
        elif not needs_gpu and "gpu" not in c:
            result.append(entry)
    return result


def add_qos_entry(
    target_config: dict[str, Any],
    name: str,
    constraint: str,
    use_for: str,
) -> bool:
    """Add a QoS entry to *target_config*.

    Entries are identified by ``(name, constraint)`` pair.  Returns
    ``True`` if added, ``False`` if the exact pair already exists.
    """
    entries = target_config.setdefault("qos", [])
    if any(e.get("name") == name and e.get("constraint") == constraint
           for e in entries):
        return False
    entries.append({"name": name, "constraint": constraint, "use_for": use_for})
    return True


def update_qos_entry(
    target_config: dict[str, Any],
    name: str,
    constraint: str | None = None,
    **updates: Any,
) -> bool:
    """Update fields on an existing QoS entry.

    Pass *constraint* to disambiguate when the same name appears with
    multiple constraints.  Without it, updates the first match.
    """
    for entry in target_config.get("qos", []):
        if entry.get("name") != name:
            continue
        if constraint is not None and entry.get("constraint") != constraint:
            continue
        entry.update(updates)
        return True
    return False


def remove_qos_entry(
    target_config: dict[str, Any],
    name: str,
    constraint: str | None = None,
) -> bool:
    """Remove a QoS entry from *target_config*.

    Pass *constraint* to disambiguate when the same name appears with
    multiple constraints.  Without it, removes the first match.
    """
    entries = target_config.get("qos", [])
    for i, entry in enumerate(entries):
        if entry.get("name") != name:
            continue
        if constraint is not None and entry.get("constraint") != constraint:
            continue
        entries.pop(i)
        return True
    return False
