"""The macOS backend: a generated Seatbelt profile.

``sandbox-exec`` is already the shape the seam wants — a wrapper command
that confines everything it execs — so there is no shim on this side.
The work is generating the SBPL, which is ordinary string building and
therefore testable (and golden-tested) on any OS.

Two rules, both learned from shipped implementations:

- **Paths never go into the profile text.** They are referenced as
  ``(param "READ_0")`` and supplied as ``-DREAD_0=<path>`` on argv, so
  no path can ever be quoted wrong or close a form early.
- **Realpath everything** before emitting, which :class:`Policy`
  guarantees: ``/tmp`` is a symlink to ``/private/tmp`` on macOS, and a
  rule naming the symlink matches nothing at all.
"""

from __future__ import annotations

import os
from collections.abc import Sequence
from dataclasses import dataclass, field

from lightcone.engine.sandbox.model import Attestation, Capability, Policy

SANDBOX_EXEC = "/usr/bin/sandbox-exec"

#: Read access macOS needs that the platform-neutral baseline does not
#: name. Constants, so they are written as literals rather than params.
_MACOS_READ_BASELINE = (
    "/System",
    "/Library/Preferences/Logging",
    "/private/etc",
    "/private/var/db/timezone",
)


def capability() -> Capability:
    """Whether ``sandbox-exec`` is present and usable on this host.

    Seatbelt has been "deprecated" since 2012 and has never been given a
    removal date, but the profile dialect does drift across releases —
    so this runs a live canary rather than trusting the file's presence.
    """
    if os.name != "posix" or not os.path.isfile(SANDBOX_EXEC):
        return Capability(kind="none", detail=f"{SANDBOX_EXEC} not present")
    import subprocess

    try:
        canary = subprocess.run(
            [SANDBOX_EXEC, "-p", "(version 1)(allow default)", "/usr/bin/true"],
            capture_output=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as e:
        return Capability(kind="none", detail=f"sandbox-exec canary failed: {e}")
    if canary.returncode != 0:
        return Capability(
            kind="none", detail=f"sandbox-exec canary exited {canary.returncode}"
        )
    return Capability(kind="seatbelt")


@dataclass(frozen=True)
class SeatbeltBackend:
    """Seatbelt, expressed as an argv rewrite."""

    capability: Capability = field(default_factory=lambda: Capability(kind="seatbelt"))

    def wrap(self, policy: Policy, argv: Sequence[str]) -> list[str]:
        params = profile_params(policy)
        return [
            SANDBOX_EXEC,
            "-p",
            generate_profile(policy),
            *(f"-D{name}={value}" for name, value in params),
            "--",
            *argv,
        ]

    def attest(self, policy: Policy) -> Attestation:
        return Attestation(
            mechanism="seatbelt",
            fs="declared",
            exec_allowlist_version=policy.exec_allowlist_version,
        )


def profile_params(policy: Policy) -> list[tuple[str, str]]:
    """The ``-D`` bindings the generated profile refers to, in order."""
    return [
        (f"{prefix}_{index}", str(path))
        for prefix, paths in (
            ("READ", policy.read),
            ("WRITE", policy.write),
            ("EXEC", policy.execute),
        )
        for index, path in enumerate(paths)
    ]


def generate_profile(policy: Policy) -> str:
    """The SBPL for *policy* — deny by default, then the three tiers."""
    lines = [
        ";; generated by lightcone-cli — the lc sandbox, Seatbelt realization",
        "(version 1)",
        "(deny default)",
        "(allow process-fork)",
        "(allow sysctl-read)",
        "(allow mach-lookup)",
        "(allow signal (target children))",
        # numpy/torch/multiprocessing all reach for these; denying them
        # breaks the scientific stack without closing any leakage channel.
        "(allow ipc-posix-shm*)",
        "(allow ipc-posix-sem*)",
        "",
        ";; network: not controlled by lc, on any platform (recorded as `allowed`)",
        "(allow network*)",
        "(allow system-socket)",
        "",
        ";; read: OS baseline + project tree + declared inputs",
        "(allow file-read*",
        *(f"  (subpath {_literal(path)})" for path in _MACOS_READ_BASELINE),
        *(f'  (subpath (param "READ_{i}"))' for i in range(len(policy.read))),
        ")",
        "",
        ";; write: the per-run HOME and the tmp scope — never the project tree",
        "(allow file-write* file-read*",
        *(f'  (subpath (param "WRITE_{i}"))' for i in range(len(policy.write))),
        ")",
        "",
        ";; execute: the environment + the versioned utility allowlist",
        "(allow process-exec*",
        *(f'  (subpath (param "EXEC_{i}"))' for i in range(len(policy.execute))),
        # dyld is the mach-o equivalent of the ELF loader tier: without
        # it nothing dynamically linked starts.
        '  (literal "/usr/lib/dyld")',
        ")",
        "",
    ]
    return "\n".join(lines)


def _literal(path: str) -> str:
    """An SBPL string literal. Only ever used on our own constants."""
    escaped = path.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
