"""Seatbelt (macOS) profile generation.

The generated SBPL realizes the same :class:`SandboxPolicy` Landlock
enforces on Linux: deny by default; read/write/exec sets realpath'd;
POSIX shm/semaphores allowed (multiprocessing); network denied except
loopback — the spec's meaning of ``denied`` keeps in-recipe
LocalCluster/torch workers working.

``sandbox-exec`` cannot nest — a recipe invoking it fails by design
(the denial UX names it plainly). The profile shape is pinned by a
golden test on Linux; enforcement is smoke-tested on macOS CI.
"""
from __future__ import annotations

from lightcone.engine.sandbox.model import SandboxPolicy

#: System paths every process needs readable (dyld, frameworks, ICU).
_MACOS_READ_BASELINE = (
    "/System",
    "/usr/lib",
    "/usr/share",
    "/private/etc",
    "/Library/Preferences/Logging",
    "/dev/urandom",
    "/dev/random",
    "/dev/null",
)


def _quote(path: object) -> str:
    return '"' + str(path).replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate_profile(policy: SandboxPolicy) -> str:
    read_paths = [*(_MACOS_READ_BASELINE), *policy.read]
    lines: list[str] = [
        ";; generated by lightcone-cli — the lc sandbox (Seatbelt realization)",
        "(version 1)",
        "(deny default)",
        "(allow process-fork)",
        "(allow sysctl-read)",
        "(allow mach-lookup)",
        "(allow ipc-posix-shm*)",
        "(allow ipc-posix-sem*)",
        "(allow signal (target children))",
        "",
        ";; read set: project + declared inputs + OS baseline",
        "(allow file-read*",
        *(f"  (subpath {_quote(p)})" for p in read_paths),
        ")",
        "",
        ";; write set: own output + scratch + tmp + per-recipe HOME",
        "(allow file-write* file-read*",
        *(f"  (subpath {_quote(p)})" for p in policy.write),
        ")",
        "",
        ";; exec set: env bin dir + versioned utility allowlist",
        "(allow process-exec*",
        *(f"  (subpath {_quote(p)})" for p in policy.execute),
        "  (literal \"/usr/lib/dyld\")",
        "  (literal \"/bin/sh\")",
        "  (literal \"/bin/bash\")",
        ")",
        "",
        ";; network: loopback only — 'denied' means non-loopback blocked",
        "(allow network-outbound (remote ip \"localhost:*\"))",
        "(allow network-bind network-inbound (local ip \"localhost:*\"))",
        "(deny network-outbound (remote ip \"*:*\"))",
        "",
    ]
    return "\n".join(lines)
