"""Deterministic Containerfile rendering.

``render()`` is a pure function of an :class:`ImageDefinition`:
byte-identical output for equal definitions (fixed layer order, sorted
packages, one whitespace style, LF endings, no timestamps) — the
rendered text is half of the image tag's identity, so any
nondeterminism here would silently fork tags.

Invariants pinned by golden tests:

* the offline ENV (``UV_OFFLINE`` …) appears **only in the final
  stage** — the build's own ``uv sync`` layer keeps network;
* the apt layer and its contract check exist iff ``system_packages``
  is nonempty;
* the dpkg snapshot is taken in the final stage, *after* the extra
  stage, so packages an extra stage installs are attested too.
"""
from __future__ import annotations

from dataclasses import dataclass

from lightcone.engine.image import constants
from lightcone.engine.image.definition import ImageDefinition
from lightcone.engine.manifest import canonical_json


@dataclass(frozen=True)
class RenderedContainerfile:
    text: str
    definition: ImageDefinition


def render(defn: ImageDefinition) -> RenderedContainerfile:
    blocks: list[str] = []

    blocks.append(
        "# generated by lightcone-cli — DO NOT EDIT\n"
        "# (rendered from pyproject.toml [tool.lightcone.image]; "
        "regenerated by `lc build`)\n"
        f"FROM {defn.base} AS env\n"
        'SHELL ["/bin/sh", "-c"]'
    )

    blocks.append(_contract_check_layer(defn))

    if defn.system_packages:
        blocks.append(_apt_layer(defn))

    blocks.append(
        "# pinned uv binary (manifest-list digest — arch-independent text)\n"
        f"COPY --from={defn.uv.copy_from_ref} /uv {constants.UV_BIN}"
    )

    blocks.append(
        "# exact interpreter, uv-managed, outside the base's control\n"
        f"ENV UV_PYTHON_INSTALL_DIR={constants.OPT_PYTHON}\n"
        f"RUN {constants.UV_BIN} python install {defn.python_version}"
    )

    blocks.append(
        "# locked sync — code-free: pyproject.toml + uv.lock are the only\n"
        "# project files that ever enter an image (G5)\n"
        f"WORKDIR {constants.PROJECT_STAGE_DIR}\n"
        "COPY pyproject.toml uv.lock ./\n"
        f"ENV UV_PROJECT_ENVIRONMENT={constants.OPT_VENV}\n"
        f"RUN {constants.UV_BIN} sync --locked --exact --no-install-project "
        f"--compile-bytecode --python {defn.python_version} "
        f"--project {constants.PROJECT_STAGE_DIR}"
    )

    final_from = "env"
    if defn.extra_stage is not None:
        final_from = "extra"
        blocks.append(
            "# user extra stage (Containerfile.extra, verbatim)\n"
            "FROM env AS extra\n" + defn.extra_stage.strip()
        )

    blocks.append(_final_stage(defn, final_from))

    text = "\n\n".join(blocks) + "\n"
    return RenderedContainerfile(text=text, definition=defn)


def _contract_check_layer(defn: ImageDefinition) -> str:
    lines = [
        "# base contract checks — each failure is a distinct exit code the",
        "# builder maps to a pointed error (never a raw build log)",
        f"RUN test -x /bin/sh || exit {constants.EXIT_NO_SH}",
        (
            "RUN if ls /lib/ld-musl-* >/dev/null 2>&1; then "
            f"echo 'musl base' >&2; exit {constants.EXIT_MUSL_BASE}; fi"
        ),
    ]
    if defn.system_packages:
        lines.append(
            "RUN command -v apt-get >/dev/null 2>&1 || "
            f"exit {constants.EXIT_NO_APT}"
        )
    return "\n".join(lines)


def _apt_layer(defn: ImageDefinition) -> str:
    pkgs = " ".join(defn.system_packages)  # already sorted in the declaration
    return (
        "# system layer — installed BEFORE uv sync so lock-level system\n"
        "# dependencies (sdist builds, rpy2-style imports) resolve here\n"
        "RUN apt-get update \\\n"
        "    && DEBIAN_FRONTEND=noninteractive apt-get install -y "
        "--no-install-recommends \\\n"
        f"       {pkgs} \\\n"
        "    && rm -rf /var/lib/apt/lists/*"
    )


def _final_stage(defn: ImageDefinition, final_from: str) -> str:
    identity = canonical_json(
        {
            "env_version": defn.env_version,
            "python_version": defn.python_version,
            "uv_version": defn.uv.version,
        }
    )
    offline_env = " ".join(f"{k}={v}" for k, v in constants.OFFLINE_ENV.items())
    path = (
        f"{constants.OPT_VENV}/bin:{constants.LC_DIR}/bin:"
        "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    )
    return (
        f"FROM {final_from} AS final\n"
        f'LABEL io.lightcone.env-version="{defn.env_version}"\n'
        "# attestation: name-pinned apt layer's actual package versions\n"
        f"RUN dpkg -l > {constants.DPKG_SNAPSHOT_PATH} 2>/dev/null "
        f"|| echo 'dpkg unavailable' > {constants.DPKG_SNAPSHOT_PATH}\n"
        f"RUN printf '%s' '{identity}' > {constants.IDENTITY_PATH}\n"
        "# world-readable: the invoking uid (rootless --userns=keep-id)\n"
        "# must be able to read everything lc baked\n"
        f"RUN chmod -R a+rX {constants.LC_DIR} {constants.OPT_PYTHON} "
        f"{constants.OPT_VENV}\n"
        "# offline overlay — FINAL stage only; earlier stages keep network\n"
        f"ENV {offline_env} \\\n"
        f"    UV_PROJECT_ENVIRONMENT={constants.OPT_VENV} \\\n"
        f"    UV_PYTHON_INSTALL_DIR={constants.OPT_PYTHON} \\\n"
        f"    PATH={path}"
    )
